version: '3'
services:

  aula_ros:
    container_name: robo
    image: ghcr.io/ufrj-nautilus/auv_ws:master
    privileged: true
    pull_policy: always
    environment:
      - DISPLAY=${DISPLAY} 
    volumes:
      - ./catkin_ws:/root/catkin_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime
    network_mode: host
    stdin_open: true
    tty: true